export const productsData = [
	{
		id: 1,
		name: "Classic Black T-Shirt",
		category: "Men",
		price: 799,
		oldPrice: 999,
		color: "Black",
		size: "M",
		type: "T-Shirt",
		image: "https://via.placeholder.com/300x400?text=Black+T-Shirt",
		isPreOrder: false,
		isOnSale: true,
		discount: 20,
		colors: ["Black", "White"],
	},
	{
		id: 2,
		name: "Casual White Hoodie",
		category: "Women",
		price: 999,
		image: "/images/hoodie1.jpg",
		color: "#fff",
		colors: ["#fff", "#ccc"],
		size: "M",
		type: "Hoodie",
	},
	{
		id: 3,
		name: "Stylish Kids T-shirt",
		category: "Kids",
		price: 499,
		image: "/images/kids1.jpg",
		color: "#ff0000",
		colors: ["#ff0000", "#ffa500"],
		size: "S",
		type: "T-shirt",
	},
	{
		id: 4,
		name: "Premium Blazer",
		category: "Men",
		price: 2999,
		image: "/images/blazer1.jpg",
		color: "#000",
		colors: ["#000", "#444"],
		size: "XL",
		type: "Blazer",
	},
	{
		id: 5,
		name: "Floral Dress",
		category: "Women",
		price: 1799,
		image: "/images/dress1.jpg",
		color: "#ffc0cb",
		colors: ["#ffc0cb", "#ff69b4"],
		size: "M",
		type: "Dress",
	},
	{
		id: 6,
		name: "Printed T-shirt",
		category: "Men",
		price: 799,
		image: "/images/tshirt1.jpg",
		color: "#008000",
		colors: ["#008000", "#90ee90"],
		size: "L",
		type: "T-shirt",
	},
];
